#!/usr/bin/env python3
"""Bundle plugin modules + a test file into one Luau script for the CLI runner.

The plugin uses Roblox's `require(script.Parent.x)`; the standalone Luau CLI has
no module loader and no `io`, so this stitches the sources together with a tiny
require shim.  Roblox-only globals are stubbed in tests/stub.luau.

    python3 tools/bundle.py tests/parser.luau > /tmp/bundle.luau
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
REQ = re.compile(r"require\(script\.Parent\.([A-Za-z_][A-Za-z0-9_]*)\)")


def load(name: str) -> str:
    return (SRC / f"{name}.luau").read_text()


def collect(entry_sources):
    """Depth-first walk of the require graph starting from the given sources."""
    order, seen = [], set()

    def visit(name):
        if name in seen:
            return
        seen.add(name)
        body = load(name)
        for dep in REQ.findall(body):
            visit(dep)
        order.append(name)

    for text in entry_sources:
        for dep in REQ.findall(text):
            visit(dep)
    return order


def main():
    test_path = pathlib.Path(sys.argv[1])
    test_src = test_path.read_text()
    stub = ((ROOT / "tests" / "mock.luau").read_text() + "\n"
            + (ROOT / "tests" / "stub.luau").read_text())

    names = collect([test_src, stub])
    out = [
        "-- generated by tools/bundle.py -- do not edit",
        "local __defs = {}",
        "local __cache = {}",
        "local function __req(name)",
        "\tif __cache[name] == nil then",
        '\t\tlocal factory = __defs[name] or error("no module " .. name)',
        "\t\t__cache[name] = factory()",
        "\tend",
        "\treturn __cache[name]",
        "end",
        stub.replace("__REQ__", "__req"),
    ]
    for name in names:
        body = REQ.sub(r'__req("\1")', load(name))
        out.append(f'__defs["{name}"] = function()')
        out.append(body)
        out.append("end")
    out.append(REQ.sub(r'__req("\1")', test_src))
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
